version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: QuizownikDatabase
    environment:
      MYSQL_ROOT_PASSWORD: BNABD
      MYSQL_DATABASE: quizownik
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 123
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql		#Persist mySQL data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql_network

volumes:
  mysql_data:
    driver: local

networks:
  mysql_network: